### ISSUE TITLE
keera-hails-reactivevalues-0.2.2.0 test suite failures

### ISSUE THREAD

**Issue by peti** [keera-studios/keera-hails#3]
Citing from http://hydra.cryp.to/build/1377268/nixlog/1/raw:

```
Test suite hlint: RUNNING...
src/Data/ReactiveValue.hs:230:3: Error: Eta reduce
Found:
  reactiveValueWrite (_, f) v = reactiveValueWrite f v
Why not:
  reactiveValueWrite (_, f) = reactiveValueWrite f

1 suggestion (5 ignored)
Test suite hlint: FAIL
```

and

```
Test suite haddock-coverage: RUNNING...
haddock-coverage: cabal: readCreateProcessWithExitCode: runInteractiveProcess: exec: does not exist (No such file or directory)
Test suite haddock-coverage: FAIL
```

**Comment by ivanperez-keera** [comment]
Thanks for reporting this. I checked the current build, and all tests are passing.

The current travis config runs the tests too, and they also passed there.

cabal should support the `exec` subcommand. Why doesn't it?

I'm closing this, please open a new ticket if it still fails. If you let me know how I can check the last build status on that project, I'll try to find out what's going on.

**Comment by peti** [comment]
`cabal` is not installed when those tests run because it's not declared as a dependency,

**Comment by ivanperez-keera** [comment]
You are absolutely right. I assumed it was always present. My bad.

I'll fix it and re-close.

**Comment by ivanperez-keera** [comment]
Hmm, I don't know exactly how to do this. This test needs to run haddock inside the package, so it executes it with cabal exec.

In my system cabal-install is provided by an ubuntu package (hvr's PPA), not installed from cabal. If I add cabal-install to the dependencies, then it will install another version of cabal-install, but I don't need it. The package database knows nothing about the version installed from the PPA.

**Comment by myroslambda** [comment]
@peti Does this solution work?

A lot has changed in Haskell since this issue was first opened. There may be a different or better way of testing for full haddock coverage. If you have proposals, please, let me know or send a PR.

**Comment by myroslambda** [comment]
Sorry, by "this solution" I mean the following change: https://github.com/keera-studios/keera-hails/commit/2453a4777c15af40df5f491c291d3d51eca2625c

**Comment by myroslambda** [comment]
Due to inactivity, and because I think the current solution may work, I am closing this issue. 

@peti, please, if it doesn't let me know so that we figure out how to fix it. Thanks!
