### ISSUE TITLE
Demo keera-hails-demos-gtk is not compilable due to lack of gtk3-helpers

### ISSUE THREAD

**Issue by cblp** [keera-studios/keera-hails#58]
```
$ stack run

Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for keera-hails-reactive-gtk3-0.6.0:
    gtk3-helpers needed, but the stack configuration has no specified version (no package with that name found,
                 perhaps there is a typo in a package's build-depends or an omission from the stack.yaml
                 packages list?)
needed due to keera-hails-demos-gtk-0.6.0 -> keera-hails-reactive-gtk3-0.6.0

Some different approaches to resolving this:


Plan construction failed.
```

**Comment by myroslambda** [comment]
I think the error here must be that https://github.com/keera-studios/gtk-helpers/tree/develop/gtk3 was not pushed to hackage, right?

**Comment by cblp** [comment]
I think pushing to Hackage is a good solution.

**Comment by myroslambda** [comment]
A preliminary package has been pushed. Can you check if it compiles now?

**Comment by cblp** [comment]
No, I've ran into another problem: glib compilation fails on OSX when compiling its supporting C code.

**Comment by myroslambda** [comment]
That looks like a problem unrelated to this package. Can we tThe glib package is part of gtk2hs.

Maybe related: https://github.com/gtk2hs/gtk2hs/issues?q=is%3Aissue+macosx+is%3Aclosed

**Comment by cblp** [comment]
Yes, that's unrelated problem. Tanks you.

**Comment by myroslambda** [comment]
Thank you!
