### ISSUE TITLE
gtk2 function notebookGetCurrentPagePassive

### ISSUE THREAD

**Issue by stewedFOSP** [keera-studios/keera-hails#6]
The notebookGetCurrentPagePassive function returns -1 in my program.

Create a new notebook n
`n <- notebookNew`
Define notebookGetCurrentPagePassive as the getter of curPageRV
`let curPageRV = ReactiveFieldReadWrite setter getter notifier
        where (ReactiveFieldRead getter _) = notebookGetCurrentPagePassive n
              setter = postGUIAsync . notebookSetCurrentPage n
              notifier io = void $ afterSwitchPage n (const io)`
When the current page is deleted and reactiveValueRead curPageRV is called, sometimes it will return -1.
`reactiveValueRead curPageRV >>= print`
When the current page is deleted, will notebookGetCurrentPagePassive always return -1? How does this function show the passive effect?

**Comment by ivanperez-keera** [comment]
A passive reactive value is one that does not actively notify events or push notifications forward. That means if you write

```
somePassiveReactiveValue =:> someOtherReactiveValue
```

In principle, probably nothing would ever get executed.

They are used in two scenarios:
1) To pair them with events and turn them into active reactive values.
2) To pair them with active reactive values (governing).

For instance, you could do something like:
```
someButtonsButtonClick `governing` somePassiveReactiveValue=:> someOtherReactiveValue
```
And that will make the RV pass the data when the button is clicked.

Does that make sense?

As for the (-1), that means the notebook currently has no pages. The underlying function giving you the (-1) is https://developer.gnome.org/gtk3/stable/GtkNotebook.html#gtk-notebook-get-current-page

**Comment by ivanperez-keera** [comment]
If you want, paste a link to your code and I'll take a look.

**Comment by xxdtl** [comment]
I needed to clear all elements on a page, and was intended to delete the current page and create a new one. I thought this would be easier, but then found that it's faster to directly delete the elements on the page. So I managed to do it without notebookGetCurrentPagePassive.
[https://gitlab.com/chupin/arpeggigon/commit/345509022c1a7eea311158361bcdbaa2fbc24c32](url)
