### ISSUE TITLE
Couldn't match type ‘model’ with ‘Maybe model0’ on GHC 8.4.3 and gtk-0.14.10

### ISSUE THREAD

**Issue by johannes-riecken** [keera-studios/keera-hails#8]
If I run `cabal install keera-hails-reactive-gtk-0.3` with ghc 8.4.3, installation of that package fails with

> src/Graphics/UI/Gtk/Reactive/Gtk2.hs:8067:30: error:
>     • Couldn't match type ‘model’ with ‘Maybe model0’
>       ‘model’ is a rigid type variable bound by
>         the type signature for:
>           treeViewSetModelReactive :: forall self model.
>                                       (TreeViewClass self, TreeModelClass model) =>
>                                       self -> ReactiveFieldWrite IO model
>         at src/Graphics/UI/Gtk/Reactive/Gtk2.hs:8066:1-113
>       Expected type: ReactiveFieldWrite IO model
>         Actual type: ReactiveFieldWrite IO (Maybe model0)
>     • In the expression: wrapMW (treeViewSetModel w)
>       In an equation for ‘treeViewSetModelReactive’:
>           treeViewSetModelReactive w = wrapMW (treeViewSetModel w)
>     • Relevant bindings include
>         treeViewSetModelReactive :: self -> ReactiveFieldWrite IO model
>           (bound at src/Graphics/UI/Gtk/Reactive/Gtk2.hs:8067:1)
>      |
> 8067 | treeViewSetModelReactive w = wrapMW (treeViewSetModel w)
>      |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

**Comment by nbrk** [comment]
[Graphics_UI_Gtk_Reactive_Gtk2_hs.diff.txt](https://github.com/keera-studios/keera-hails/files/2729624/Graphics_UI_Gtk_Reactive_Gtk2_hs.diff.txt)
